using System.Collections;
using System.Collections.Generic;
using UnityEngine;
namespace Caress
{
    public class Player {

        public string username;
        /**
         * Only id for user generated by server
         **/
        public string uid;

        public List<Chess> ownedChess;

        public int blood;

        /**
         * 响应trigger
         **/
        public void onEndTurn() {
            //emit socket

        }
    }
    
    
    public enum ColorType {
        NONE,
        RED,
        GREEN,
        BLUE
    }
}